[package]
name = "recbox"
version = "0.1.0"
edition = "2021"
author = "xermicus"
repository = "https://github.com/xermicus/recbox"
description = "simple audio recorder"

[dependencies]
env_logger = "0.11.5"
hound = "3.5.1"
jack = "0.13.0"
log = "0.4.22"
